name: Python SQL GitActions

on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install python packages
      run:
          python -m pip install --upgrade pip
          pip install pandas
          pip install beautifulsoup4 requests
          pip install sqlalchemy
          pip install mysql-connector-python
    - name: execute py script
      run: 
        python scraping_script.py